import type { Investigation, Client, IOC, TimelineEvent } from '@/types'
import { formatDateTime } from './utils'

/**
 * Generates a full Markdown investigation report
 */
export function exportToMarkdown(
  investigation: Investigation,
  client: Client,
  iocs: IOC[],
  timeline: TimelineEvent[],
  draftEmail: string
): string {
  const sev = investigation.severity.toUpperCase()
  const status = investigation.status.replace('_', ' ').toUpperCase()
  const verdict = investigation.verdict
    ? investigation.verdict.replace(/_/g, ' ').toUpperCase()
    : 'PENDING'

  const lines: string[] = []

  // Header
  lines.push(`# Investigation Report — ${client.name}`)
  lines.push(``)
  lines.push(`> **⚠️ CONFIDENTIAL — ${client.short_code} — DO NOT SHARE ACROSS CLIENTS**`)
  lines.push(``)
  lines.push(`| Field | Value |`)
  lines.push(`|---|---|`)
  lines.push(`| **Case Number** | ${investigation.case_number} |`)
  lines.push(`| **Alert** | ${investigation.alert_name} |`)
  lines.push(`| **Client** | ${client.name} (${client.short_code}) |`)
  lines.push(`| **Severity** | ${sev} |`)
  lines.push(`| **Status** | ${status} |`)
  lines.push(`| **Verdict** | ${verdict} |`)
  lines.push(`| **Triggered** | ${formatDateTime(investigation.triggered_at)} |`)
  lines.push(`| **Analyst** | ${investigation.assigned_analyst || 'ECI-SOC'} |`)
  lines.push(`| **Generated** | ${formatDateTime(new Date().toISOString())} |`)
  lines.push(``)

  // Investigation fields
  if (Object.keys(investigation.field_data || {}).length > 0) {
    lines.push(`## Investigation Fields`)
    lines.push(``)
    lines.push(`| Field | Value |`)
    lines.push(`|---|---|`)
    for (const [key, value] of Object.entries(investigation.field_data)) {
      const label = key.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase())
      lines.push(`| ${label} | \`${value}\` |`)
    }
    lines.push(``)
  }

  // Observations
  if (investigation.observations?.length) {
    lines.push(`## Observations`)
    lines.push(``)
    investigation.observations.forEach((obs, i) => {
      lines.push(`${i + 1}. ${obs}`)
    })
    lines.push(``)
  }

  // IOCs
  if (iocs.length > 0) {
    lines.push(`## Indicators of Compromise (IOCs)`)
    lines.push(``)
    lines.push(`| Type | Value (Defanged) | Source | Blocked | Notes |`)
    lines.push(`|---|---|---|---|---|`)
    for (const ioc of iocs) {
      const val = ioc.value_defanged || ioc.value_raw
      lines.push(
        `| ${ioc.type} | \`${val}\` | ${ioc.source || '-'} | ${ioc.blocked ? '✅ Yes' : '❌ No'} | ${ioc.notes || '-'} |`
      )
    }
    lines.push(``)
  }

  // Timeline
  if (timeline.length > 0) {
    lines.push(`## Timeline`)
    lines.push(``)
    for (const event of timeline) {
      lines.push(`- **${formatDateTime(event.created_at)}** — ${event.description}`)
    }
    lines.push(``)
  }

  // Verdict & Summary
  lines.push(`## Verdict`)
  lines.push(``)
  lines.push(`**${verdict}**`)
  lines.push(``)
  if (investigation.summary) {
    lines.push(investigation.summary)
    lines.push(``)
  }

  // Draft Email
  lines.push(`## Draft Email`)
  lines.push(``)
  lines.push('```')
  lines.push(draftEmail)
  lines.push('```')
  lines.push(``)
  lines.push(`---`)
  lines.push(`*Generated by SOC-Companion | ECI-SOC | ${new Date().toISOString()}*`)

  return lines.join('\n')
}

/**
 * Downloads a string as a .md file
 */
export function downloadMarkdown(content: string, filename: string) {
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename.endsWith('.md') ? filename : `${filename}.md`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

/**
 * Copies text to clipboard and returns success boolean
 */
export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text)
    return true
  } catch {
    // Fallback for older browsers
    const ta = document.createElement('textarea')
    ta.value = text
    ta.style.position = 'fixed'
    ta.style.opacity = '0'
    document.body.appendChild(ta)
    ta.focus()
    ta.select()
    const ok = document.execCommand('copy')
    document.body.removeChild(ta)
    return ok
  }
}
